name: WebhookAction
version: '1.0'
main: com.wairesd.webhookaction.Main
api-version: '1.20'
commands:
    webhook:
        description: Sends a message to a Discord webhook.
        usage: /<command> <message>